package com.tencent.kgvmp.report;

public enum e {
    VMP_SUCCESS(0),
    CANNT_FIND_LOCAL_CONFIG(1),
    CANNT_READ_LOCAL_CONFIG(2),
    READ_LOCAL_CONFIG_EXCEPTION(3),
    GET_LOCAL_CONFIG_EMPTY(4),
    PARSE_JSON_CONFIG_EXCEPTION(5),
    PARSE_JSON_VALUE_EXCEPTION(6),
    START_SERVER_FAILED(7),
    INIT_THREAD_TIMEOUT(8),
    REALLY_INIT_EXCEPTION(9),
    CONTEXT_IS_NULL(10),
    DOWNLOAD_CONFIG_EXCEPTION(11),
    DOWNLOAD_CONFIG_EMPTY(12),
    DOWNLOAD_CONFIG_SAVE_FILE_EXCEPTION(13),
    DOWNLOAD_CODE_EXCEPTION(14),
    DOWNLOAD_CONFIG_CONTENT_NOT_JSON(15),
    GET_EXTERNAL_DIR_FAILED(16),
    DEVICE_IS_REAL(20),
    DEVICE_IS_NOT_REAL(21),
    DEVICE_IS_UNKOWN(22),
    DEVICE_CONFIG_GET_EXCEPTION(23),
    DEVICE_CONFIG_AVAILABLE_IS_FALSE(24),
    SAMSUNG_GAME_SDK_MANAGER_IS_NOT_AVAILABLE(401),
    SAMSUNG_GAME_SDK_MANAGER_CAN_NOT_INITIALIZE(402),
    SAMSUNG_GAME_SDK_MANAGER_REGISTER_CALLBACK_FALSE(403),
    SAMSUNG_GAME_SDK_MANAGER_IS_NOT_REGISTERED(404),
    SAMSUNG_GAME_SDK_MANAGER_CANCEL_REGISTERED_FAILED(405),
    SAMSUNG2_GAME_SERVICE_HELPER_IS_NULL(451),
    SAMSUNG2_GAME_SERVICE_HELPER_INIT_FAILED(452),
    SAMSUNG2_GAME_SERVICE_HELPER_REGISTERED_FAILED(453),
    SAMSUNG2_GAME_SERVICE_HELPER_UN_BIND_SUCC(454),
    HUAWEI2_MOBILE_NOT_SUPPORT_SDK(501),
    XIAOMI_MOBILE_NOT_SUPPORT_SDK(601),
    XIAOMI_MOBILE_REGISTER_FAILED(602),
    XIAOMI_MOBILE_UNREGISTER_FAILED(603),
    XIAOMI_MOBILE_NOTIFY_GAME_SECENE_FAILED(604);
    
    private int code;

    private e(int i) {
        this.code = i;
    }

    public int getCode() {
        return this.code;
    }

    public String getStringCode() {
        return String.valueOf(this.code);
    }
}
